version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://db:27017/spotify # MongoDB URI with service name and database name
    depends_on:
      - db
    networks:
      - spotify-music

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    depends_on:
      - backend
    networks:
      - spotify-music

  db:
    image: mongo:latest  # Use MongoDB image
    container_name: mongo-container
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo-data:/data/db  # Volume for MongoDB data
    networks:
      - spotify-music

volumes:
  mongo-data:  # Volume definition for MongoDB

networks:
  spotify-music:  # Custom network definition
    driver: bridge
